spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # Esto pa que se ejecute el script
      schema-locations: classpath:sql/01_schema.sql