spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create # Crea las tablas al arrancar
    show-sql: true # Para ver qué hace Hibernate en la consola